name: my_first_8772B787-9148-4C50-9324-178F60C50F70

# label used for menu selection
label: gFirst Skillet for Panhandler

description: |
  What am I gonna do here?!
type: panos

labels:
  collection: Example Skillets

variables:
  - name: ADDR_OBJ_NAME
    description: Address Object Name
    default: panos-01
    type_hint: text
    help_text: This is the object name.
  - name: ADDR_OBJ_IP_Address
    description: IP Address
    default: 2.2.2.0/24
    type_hint: text
    help_text: This is the IP Address with Prefix (/xx)

snippets:
  - name: set_addrobj
    xpath: /config/devices/entry[@name='localhost.localdomain']/deviceconfig/system
    file: myobj.xml
    #when: hostname != FW_NAME