# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: add_ACL_1
# label used for menu selection
label: Add Security Policy Rules
description: Adds two Security Policies

# type of device configuration
# common types are panorama, panos, and template
# https://github.com/PaloAltoNetworks/panhandler/blob/develop/docs/metadata_configuration.rst
type: panos
# preload static or default-based templates
extends:

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - gSkillets

# ---------------------------------------------------------------------
# end of preamble section

# variables section
# ---------------------------------------------------------------------
# variables used in the configuration templates
# type_hint defines the form field used by panhandler
# type_hints can be text, ip_address, or dropdown
variables:
  - name: hostname
    description: Firewall hostname
    default: myFirewall
    type_hint: text
  - name: choices
    description: sample dropdown list
    default: choices
    type_hint: dropdown
    dd_list:
      - key: option1
        value: option1
      - key: option2
        value: option2
# ---------------------------------------------------------------------
# end of variables section

# snippets section
# ---------------------------------------------------------------------
# snippets used for api configuration including xpath and element as file name
# files will load in the order listed
# NOTE: The following snippets are auto-generated and ordered automatically.
# Changing the content of the snippet may be necessary, but do NOT change the order

# There is a variable called snippets that we can use to auto-generate this section for us
snippets:

  - name: entry-988883
    xpath: /config/devices/entry[@name="localhost.localdomain"]/vsys/entry[@name="vsys1"]/rulebase/security/rules
    element: |-
        <entry name="MacMini-1" uuid="642b3ce1-f6a6-4e5f-ab9e-efb72ac0039c">
                          <to>
                            <member>trusted</member>
                          </to>
                          <from>
                            <member>untrusted</member>
                          </from>
                          <source>
                            <member>any</member>
                          </source>
                          <destination>
                            <member>my-dns</member>
                          </destination>
                          <source-user>
                            <member>any</member>
                          </source-user>
                          <category>
                            <member>any</member>
                          </category>
                          <application>
                            <member>any</member>
                          </application>
                          <service>
                            <member>TCP-8031</member>
                          </service>
                          <hip-profiles>
                            <member>any</member>
                          </hip-profiles>
                          <action>allow</action>
                        </entry>

  - name: entry-766750
    xpath: /config/devices/entry[@name="localhost.localdomain"]/vsys/entry[@name="vsys1"]/rulebase/security/rules
    element: |-
        <entry name="Allow gutil1 SMTP Out-1" uuid="b242c273-49ae-4bbd-a4b2-97b393c7efe0">
                          <to>
                            <member>untrusted</member>
                          </to>
                          <from>
                            <member>trusted</member>
                          </from>
                          <source>
                            <member>192.168.77.14</member>
                          </source>
                          <destination>
                            <member>any</member>
                          </destination>
                          <source-user>
                            <member>any</member>
                          </source-user>
                          <category>
                            <member>any</member>
                          </category>
                          <application>
                            <member>smtp</member>
                          </application>
                          <service>
                            <member>smtp</member>
                          </service>
                          <hip-profiles>
                            <member>any</member>
                          </hip-profiles>
                          <action>allow</action>
                          <disabled>yes</disabled>
                        </entry>


# ---------------------------------------------------------------------
# end of snippets section