name: get_addr_obj_1

# label used for menu selection
label: Find Address Object

description: |
  Find one address object and get the value (Skillet Testing)
type: panos
cmd: show

labels:
  collection: gSkillets

variables:
  - name: ADDR_OBJ_NAME
    description: Address Object Name
    default: panos-01
    type_hint: text
    help_text: This is the object name you want to find.

snippets:
  - name: get_addrobj
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/address
    file: addr-obj.xml
    #when: hostname != FW_NAME