name: addr_obj_1

# label used for menu selection
label: Add Address Object

description: |
  Add one address object (Skillet Testing)
type: panos

labels:
  collection: gSkillets

variables:
  - name: ADDR_OBJ_NAME
    description: Address Object Name
    default: panos-01
    type_hint: text
    help_text: This is the object name.
  - name: ADDR_OBJ_CIDR
    description: IP Address in CIDR notation (/xx)
    default: 2.2.2.0/24
    type_hint: cidr
    help_text: This is the IP Address with Prefix (/xx)

snippets:
  - name: set_addrobj
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/address
    file: addr-obj.xml
    #when: hostname != FW_NAME